name: Continuous Integration - PR's Tests

on:
  push:
    branches: 
      - 68-code-climate
jobs:

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Modules
      run: npm install
      working-directory: server
    - name: Test & publish code coverage
      working-directory: server
      uses: marsam/codeclimate-action@master
      env:
        with:
          reporter-id: ${{ secrets.CC_REPORTER_ID }}
          command: npm run test
    